version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: iot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"   # DB_PORT la file cau hinh trong .env, hien tai no se mount vao port 3306 cua container
    volumes:
      - mysql_data:/var/lib/mysql
    command: --log-bin-trust-function-creators=1

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: iot_mosquitto
    env_file:
      - .env
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mqtt/config:/mosquitto/config
      - ./infra/mqtt/init.sh:/init.sh:ro
    entrypoint: ["/init.sh"]
    restart: unless-stopped

volumes:
  mysql_data:

